### ISSUE TITLE
Unable to find type [Pester.OutputTypes].

### ISSUE THREAD

**Issue by eliassal** [SQLDBAWithABeard/JupyterNotebooks#2]
Hi Rob, I followed your session yesterday, whenever I run
`Invoke-DbcCheck -SqlInstance $SQL1 -SqlCredential $SqlCredential -Check AutoClose`
or 
`Invoke-DbcCheck -SqlInstance $SQL1 -SqlCredential $SqlCredential -Check LogfileSize`

I get
```
Unable to find type [Pester.OutputTypes].
At line:219 char:9
```
Thanks for your help

**Comment by eliassal** [comment]
Hi Rob, any feedback before closing please?

**Comment by SQLDBAWithABeard** [comment]
This is a dbachecks issue that has been resolved

**Comment by eliassal** [comment]
OK thanks, resolved in dbatools? so I need a new version of the dbatools or your notebook?

**Comment by eliassal** [comment]
It is working now. But can you please tell me where can one find details of messages returned by 
Invoke-DbcCheck -SqlInstance $SQLInstance -Check LogfileSize
I ran it on a 2k16 sql, I got some lines as follows

`Invoke-DbcCheck -SqlInstance $SQLInstance -Check LogfileSize`

> [+] Database Admin Should have no log files larger than 50% of the average of DataFiles on SQL2K16 32ms
>  [+] Database AdventureWorks2012 Should have no log files larger than 50% of the average of DataFiles on SQL2K16 8ms

......
but when I check the properties of the DB AdventureWorks2012  for example, I have files Data 100Mb, log is 40MB so 40 is not greater than 50% of the data file
Thanks in advance

**Comment by SQLDBAWithABeard** [comment]
That is the correct result then. 

The LogFileSize check will fail if the Log File size is greater than 50% of the Data File Size, this database has a log file size of 40%

If you wish to see a failing check then you can set the Config you will see a failure


Note it needs to be 0.3 for 30% until I fix the bug

Set-DbcConfig -Name policy.database.logfilesizepercentage -Value 0.3

![image](https://user-images.githubusercontent.com/6729780/128597840-ad83dd2c-f10f-45f4-9f59-29f093a2bd57.png)

**Comment by eliassal** [comment]
OK got it, thanks very mush
